# Python Basics - 5 Exercises

---

## Exercise 1: List Operations

Create a list of numbers from 1 to 10. Then:
1. Use slicing to get only the even-indexed elements (0, 2, 4, ...)
2. Use a list comprehension to square each number in the original list
3. Calculate the sum of all squared numbers

In [1]:
# Create list
nums = list(range(1, 11))
print("Original list:", nums)

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
# 1. Even-indexed elements
even_indexed = nums[::2]
print("Even-indexed:", even_indexed)

Even-indexed: [1, 3, 5, 7, 9]


In [3]:
# 2. Square each number
squared = [x**2 for x in nums]
print("Squared:", squared)

Squared: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [4]:
# 3. Sum of squared numbers
total = sum(squared)
print("Sum of squares:", total)

Sum of squares: 385


---
## Exercise 2: Dictionary Basics

Create a dictionary with 5 fruits as keys and their prices as values. Then:
1. Print all fruit names
2. Find the most expensive fruit using max()
3. Add 10% to all prices using a dictionary comprehension

In [5]:
# Create dictionary
fruits = {'apple': 1.2, 'banana': 0.5, 'orange': 0.8, 'grape': 2.0, 'mango': 1.5}
print("Original prices:", fruits)

Original prices: {'apple': 1.2, 'banana': 0.5, 'orange': 0.8, 'grape': 2.0, 'mango': 1.5}


In [6]:
# 1. Print all fruit names
print("Fruit names:", list(fruits.keys()))

Fruit names: ['apple', 'banana', 'orange', 'grape', 'mango']


In [7]:
# 2. Most expensive fruit
most_expensive = max(fruits, key=fruits.get)
print(f"Most expensive: {most_expensive} at ${fruits[most_expensive]}")

Most expensive: grape at $2.0


In [8]:
# 3. Add 10% to all prices (and enjoy python's numeric issues..)
increased_prices = {fruit: price * 1.1 for fruit, price in fruits.items()}
print("Prices after 10% increase:", increased_prices)

Prices after 10% increase: {'apple': 1.32, 'banana': 0.55, 'orange': 0.8800000000000001, 'grape': 2.2, 'mango': 1.6500000000000001}


---
## Exercise 3: Array Creation and Basic Operations

Create a NumPy array of 10 random integers between 1 and 50. Then:
1. Find the mean, min, and max values
2. Count how many numbers are greater than 25
3. Replace all numbers less than 20 with 0

In [9]:
import numpy as np

# Create random array
np.random.seed(42)
arr = np.random.randint(1, 51, 10)
print("Original array:", arr)

Original array: [39 29 15 43  8 21 39 19 23 11]


In [10]:
# 1. Mean, min, max
print(f"Mean: {arr.mean():.2f}")
print(f"Min: {arr.min()}")
print(f"Max: {arr.max()}")

Mean: 24.70
Min: 8
Max: 43


In [11]:
# 2. Count numbers > 25
count = (arr > 25).sum()
print(f"Numbers greater than 25: {count}")

Numbers greater than 25: 4


In [12]:
# 3. Replace numbers < 20 with 0
arr[arr < 20] = 0
print("After replacement:", arr)

After replacement: [39 29  0 43  0 21 39  0 23  0]


---
## Exercise 4: 2D Array Slicing

Create a 4x4 matrix with values from 1 to 16. Then:
1. Extract the first two rows
2. Extract the last column
3. Extract the 2x2 center submatrix (elements from rows 1-2, columns 1-2)
4. Calculate the sum of each row

In [13]:
import numpy as np

# Create 4x4 matrix
matrix = np.arange(1, 17).reshape(4, 4)
print("Original matrix:")
print(matrix)
print()

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



In [14]:
# 1. First two rows
first_two_rows = matrix[:2, :]
print("First two rows:")
print(first_two_rows)
print()

First two rows:
[[1 2 3 4]
 [5 6 7 8]]



In [15]:
# 2. Last column
last_column = matrix[:, -1]
print("Last column:", last_column)
print()

Last column: [ 4  8 12 16]



In [16]:
# 3. Center 2x2 submatrix
center = matrix[1:3, 1:3]
print("Center 2x2 submatrix:")
print(center)
print()

Center 2x2 submatrix:
[[ 6  7]
 [10 11]]



In [17]:
# 4. Sum of each row
row_sums = matrix.sum(axis=1)
print("Sum of each row:", row_sums)

Sum of each row: [10 26 42 58]


---
## Exercise 5: Simple DataFrame Operations

Create a DataFrame with 5 students (Name, Age, Grade). Then:
1. Add a new column "Pass" that is True if Grade >= 60, False otherwise
2. Calculate the average grade
3. Filter to show only students who passed
4. Sort by Grade in descending order

In [18]:
import pandas as pd

# Create DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [20, 21, 19, 22, 20],
    'Grade': [85, 55, 92, 45, 78]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
print()

Original DataFrame:
      Name  Age  Grade
0    Alice   20     85
1      Bob   21     55
2  Charlie   19     92
3    Diana   22     45
4      Eve   20     78



In [19]:
# 1. Add "Pass" column
df['Pass'] = df['Grade'] >= 60
print("DataFrame with Pass column:")
print(df)
print()

DataFrame with Pass column:
      Name  Age  Grade   Pass
0    Alice   20     85   True
1      Bob   21     55  False
2  Charlie   19     92   True
3    Diana   22     45  False
4      Eve   20     78   True



In [20]:
# 2. Calculate average grade
avg_grade = df['Grade'].mean()
print(f"Average grade: {avg_grade:.2f}")
print()

Average grade: 71.00



In [21]:
# 3. Filter passing students
passing_students = df[df['Pass'] == True]
print("Students who passed:")
print(passing_students)
print()

Students who passed:
      Name  Age  Grade  Pass
0    Alice   20     85  True
2  Charlie   19     92  True
4      Eve   20     78  True



In [22]:
# 4. Sort by Grade descending
sorted_df = df.sort_values('Grade', ascending=False)
print("Sorted by Grade (descending):")
print(sorted_df)

Sorted by Grade (descending):
      Name  Age  Grade   Pass
2  Charlie   19     92   True
0    Alice   20     85   True
4      Eve   20     78   True
1      Bob   21     55  False
3    Diana   22     45  False
